### ISSUE TITLE
.IPA

### ISSUE THREAD

**Issue by RoboNutterjack** [osxusr/nalu935#10]
osxusr, i know that you are probably going to delete this issue but i was hoping that you wold please give us the .ipa file so then we could SSH into our devices and install Cydia via PuTTY. 

Thanks if you can,

RoboNutterjack

**Comment by lordsba** [comment]
me also I hope so Lolol

**Comment by osxusr** [comment]
in the future, yes there will be a ipa, there isn't one right now because there isn't a story board or anything to have a UI, someone has to make it and it won't me be, once more 9.3.5 become available i can add them

**Comment by pozzdonnz79** [comment]
Dude actually he is the release but you just find your device offset that it if you can't do shit pls keep you mouth and ur finger shut so he is our hope if you still anynoy you will be fucked by my fucking virus believe me u just search kernel offset then use home Depot to jailbreak oh yes nalu need story board too if you can find fucking offset you can have it but if u can't stay tuned don't do shit I hope u understand what I'm talking about OMG Jesus install via putty damn u fucking genuies I give u trump up u are the best install via putty lol I can't stop laughing

**Comment by pozzdonnz79** [comment]
And I found your address ass holes
