### ISSUE TITLE
Collaberation

### ISSUE THREAD

**Issue by OlaySecTeam** [osxusr/nalu935#11]
Hello, we are a team of 7 people. 
We are wondering if you would like to collaborate with you.

Atm we are:
Making your application GUI
Making a better website for you

Contact us:
OlayTeam Twitter:

http://bit.ly/2qmT0Dw

OlayTeam Reddit

 FYI We do have null pixel on our team.

 Thanks!!
-OlayTeam

**Comment by osxusr** [comment]
i dont need help with my website, if you wanna collab on nalu935, fork it and make your changes and then request a merge pull request
