### ISSUE TITLE
Crash on launch!

### ISSUE THREAD

**Issue by ByteGig** [osxusr/nalu935#4]
nalu b4 crashes on launch as if unsigned, works after like 3 relaunches

**Comment by osxusr** [comment]
device ?

**Comment by osxusr** [comment]
@ByteGig Device ?

**Comment by ByteGig** [comment]
sorry it was an iPhone 4S

**Comment by osxusr** [comment]
@ByteGig try removing the app, reboot your device, reinstall the app with impactor and trust the apple id you used

**Comment by ByteGig** [comment]
Sorry it works but may be one off
