### ISSUE TITLE
cannot find .app/info.plist

### ISSUE THREAD

**Issue by bananaNuns** [osxusr/nalu935#6]
I downloaded the folder and zipped it . then changed the .zip extension to .ipa and tried to install with cydia impactor . 
The impactor popped that error "cannot find .app/info.plist"

im kind of new to all this and i really want to help with this jailbreak 

i have an ipad 2.1 ios 9.3.5

**Comment by osxusr** [comment]
ill fix it in the future, its not a big deal right now and its not complete so you shouldn't even be trying to install it right now

**Comment by king4q** [comment]
Banana nuns if you provide me the IPA I'll fix the issue it's the fact that the folders aren't properly made Aka it could have like two folders or one extra folder and it's not supposed to just link me the IPA and I will fix it!

**Comment by bananaNuns** [comment]
https://www.dropbox.com/s/t4wi7mg10ochdau/nalu935-master.zip?dl=0

i just downloaded the folder and then changed the extension to ipa

**Comment by osxusr** [comment]
thats not how it works, its not ready so stop

**Comment by king4q** [comment]
Banana nuns your link isn't available private message me with a link that nobody can take down
