### ISSUE TITLE
it's real?

### ISSUE THREAD

**Issue by erumia** [osxusr/nalu935#7]
これは本物でしょうかね？
それこそこういう話題を出して自分の認知度を上げたい的な感じをやってる人もいますからねぇ…
本物であるならやはりそこはios9.3.5のカーネル偽装なし、初期化しての更新後に脱獄作業を動画で出して頂きたいです〜！
（´-з-）

**Comment by erumia** [comment]
まぁ、作業と言うよりはデモ動画(demo video)を出して欲しいですね〜
\( ˙꒳​˙ \三/ ˙꒳​˙)/

**Comment by bananaNuns** [comment]
Well i dont have any clue of what you said but according to him : https://youtu.be/BKWukPjc3NA
Its real but its not ready yet

**Comment by osxusr** [comment]
yes its real, its not finished, stop opening issues that aren't issues
