### ISSUE TITLE
How to install it via Cydia Impactor?

### ISSUE THREAD

**Issue by Wolfaks** [osxusr/nalu935#8]
Hello. How to install it via Cydia Impactor? I connected my device, but which file should I select in the Cydia Impactor?

**Comment by v0idst4r** [comment]
Kys

**Comment by pozzdonnz79** [comment]
Do u have. .IPA file ? If u have IPA download cydiaimpactor from cydiaimpactor.com then launch cydia impactor on desktop drag .IPA file into cydia impactor it will ask UR apple I'd and password done has been installed ipa. File OK I will explain u what is IPA IPA file is app like download install from appstore such line whatsapl is IPA file that it don't forget to trust in setting general scroll down looking device &management open then looking UR apple I'd just installed then Pree trust done

**Comment by v0idst4r** [comment]
Good luck finding an IPA then if it doesnt even exist lmfao

**Comment by pozzdonnz79** [comment]
So if u have nalu935.IPA pls share me upload to dropbox or google drive thank you

**Comment by v0idst4r** [comment]
https://mega.nz/#!s95lXSTL!uABgcZ5e796ZMr1StemGz7twIxdIeG1Gus_0pnJiI0Q

**Comment by Wolfaks** [comment]
Writes an error: nalu935.ipa not are zip archive 29.04.2017, 19:00, "Void" <notifications@github.com>:https://mega.nz/#!s95lXSTL!uABgcZ5e796ZMr1StemGz7twIxdIeG1Gus_0pnJiI0Q—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by v0idst4r** [comment]
You should never install random IPAs, you can very easily install malware,
backdoors, remote access trojans, etc.

**Comment by amaan244713** [comment]
can i help u

**Comment by amaan244713** [comment]
.....?

**Comment by pozzdonnz79** [comment]
😂😂😂😂😂😂😂

**Comment by pozzdonnz79** [comment]
This guys make fake.IPA you can do also just create new folder and change extention to .IPA that it then rename nalu935.IPA fuck u sob

**Comment by v0idst4r** [comment]
Do you have fucking autism?

**Comment by v0idst4r** [comment]
`dd if=/dev/urandom of=nalu935.ipa count=4k`

**Comment by Kratos9803** [comment]
@v0idst4r your a fucking asshole just because someone is autistic doesn't mean they're retarded.  In fact I'm autistic myself and I know how to read/write the swift code language in Xcode.

**Comment by v0idst4r** [comment]
Oh sorry I should've called him retarded instead. Also swift is horrible.

**Comment by Kratos9803** [comment]
I'd like to see you write it

**Comment by v0idst4r** [comment]
Ok, you're a retard

**Comment by Kratos9803** [comment]
If I'm so retarded how come I'm in college how come I can read and write swift.  Yes swift was shit because it was released when iOS 7 came out stupid.

**Comment by v0idst4r** [comment]
Idk you're the one who asked

**Comment by Kratos9803** [comment]
You do to know the answer to those questions it's because I'm smarter than you.

**Comment by v0idst4r** [comment]
English please?
